#
# Welcome to the Artsy theme for Jekyll!
#

# Site settings
title: Your awesome title
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# URL to a site-wide logo (e.g. /assets/your-company-logo.jpg)
logo: /assets/img/something.jpeg

# Social profiles
social:
  name: {{ site.author }}
  links:
    - https://github.com/ebkalderon
    - https://www.linkedin.com/in/ebkalderon
    - https://www.reddit.com/user/ebkalderon
    - https://keybase.io/ebkalderon

# Post settings
collections:
  posts:
    output: true
    permalink: /blog/:categories/:year/:month/:day/:title/

# Sass settings
sass:
  sass_dir: ./_scss

# Build settings
markdown: kramdown
kramdown:
    auto_ids: true
theme: artsy
remote_theme: ebkalderon/artsy
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - artsy.gemspec
